### PR TITLE
Fixed BLC icon

### PR DESCRIPTION
**Pull request by HeliumOctahelide**
I submitted a wrong pull request before. Thanks @Horsty80 for pointing it out.

### CODE REVIEW

**Review by Horsty80 — APPROVED** [review]
It seems legit to me :)

**Comment by Horsty80** [comment]
Just add some screen that this fix is working fine ✌️

Capture d’écran 2024-08-11 à 15 26 21

**Comment by andrewgioia** [comment]
Sorry all, I think this can be closed now?

**Comment by Horsty80** [comment]
Yes ✌️

**Pull request closed without merging**
