### PR TITLE
Keyrune .scss version

### PR DESCRIPTION
**Pull request by jordanbrauer**
Hey man! 

Hope this is up to snuff for ya'. It's about 12 hours of work, so the commit messages are sort of messy... especially "Completed conversion commit." ahaha.

I fixed/changed up a few things in addition to converting it to `scss` that may (or may not) be a more scalable solution for this font package. :)

I didn't do the README or anything yet though. There are also more features I would like to add later as well, but I really gotta go to bed lol!

Hit me up here or on [twitter](https://twitter.com/jordbrauer) if you wanna talk!

### CODE REVIEW

**Comment by jordanbrauer** [comment]
@andrewgioia All ready to go friend!

**Comment by andrewgioia** [comment]
Thanks @jordanbrauer, sorry I haven't taken a look at this yet! I should be able to tomorrow much more fully. This is excellent, I'm inclined to merge it into master and keep the Less and Sass files in separate folders like FontAwesome does as maintaining two branches seems like it could get to be a headache going forward.

**Comment by jordanbrauer** [comment]
@andrewgioia Sounds good man. No worries. :)

**Comment by jordanbrauer** [comment]
@andrewgioia Hey man, was curious if you had gotten a chance to looking over my PR yet.

**Comment by andrewgioia** [comment]
@jordanbrauer I'm sorry for the extreme delay here. After looking through this, I realize you sent it with the intent of having SASS in a separate branch. However, I would rather have everything in one branch to minimize maintenance down the line. Sorry for any confusion and added work here, can you please do the following though:

1. Add the existing LESS files back into this PR with no changes
2. Don't submit any changes to the keyrune.css and keyrune.min.css files (untrack your changes to them in this PR)
3. Only add changes to .gitignore relevant to the SASS additions
4. Revert the readme back to the original, this one is referencing the SASS branch that I think was your original intent
5. Remove the gulpfile for now (let's keep this PR to just the SASS additions)

Thanks again for your excellent work, the SASS itself looks otherwise good to go. Let me know if you have any questions or if there's anything I can help with too.

**Comment by jordanbrauer** [comment]
@andrewgioia Pulled your updates down and committed my changes.

However there are a few conflicting files it says. I am not sure what they would be conflicting with though, because I pulled them down from your repo, and they're the font files to boot which I have never touched haha. Not sure what's up with the `package.json` haha.

**Comment by andrewgioia** [comment]
@jordanbrauer I merged in your changes after fixing some odd conflicts, I'm not sure how they got introduced but it should be all good now. Thanks again for doing all the heavy lifting here, I'll make sure to maintain both on my incremental updates.

**Comment by jordanbrauer** [comment]
@andrewgioia Right on! Not a problem, I loved writing it.

In case you hadn't noticed already (I am sure you have), to add a new symbol class to the SASS version, simply add a new entry to the setlist array in `_variables.scss` for the symbol you've added to the font file and the rest will take care of itself! :)

**Pull request merged**
